### ISSUE TITLE
linter: ensure parity with other repos

### ISSUE THREAD

**Issue by NightTsarina** [Tina-pm/ansible-playbooks#11]
While reviewing #7, I realised that YAML files are not being linted properly, as we are missing a configuration file for it.

Plus, I still don't know how to properly lint this repo without manually adding the dependencies to the search path, as I cannot get `ansible-lint` to fetch them automatically. This is done correctly in the Github Action, so I would like to have parity with our CLI tools.

**Comment by NightTsarina** [comment]
@dato Could you take this one?

**Comment by dato** [comment]
@NightTsarina I'm not sure I can reproduce. This is what I did, on the playbooks repo:

```con
❯ mv ~/.ansible ~/.ansible.off
❯ rm -rf ~/.cache/ansible-compat
❯ sudo apt install -t trixie ansible-lint python3-wcmatch=8.5.1-1

❯ ansible-lint --version
ansible-lint 24.10.0 using ansible-core:2.17.5 ansible-compat:24.9.1 ruamel-yaml:0.18.6 ruamel-yaml-clib:0.2.8

❯ git rev-parse @
598e6ec6b6bd64e1232d19136535820d48e242ff

❯ ansible-lint
Passed: 0 failure(s), 0 warning(s) on 50 files. Profile 'production' was required, and it passed.

❯ find ~/.ansible
/home/dato/.ansible
/home/dato/.ansible/tmp
/home/dato/.ansible/galaxy_cache
/home/dato/.ansible/galaxy_cache/api.json

❯ find ~/.cache/ansible-compat | wc -l
422

❯ find ~/.cache/ansible-compat -name blackbox.yml.j2 -o -name toml_filter.py
/home/dato/.cache/ansible-compat/cf2757/collections/ansible_collections/tina_pm/common/roles/prometheus_blackbox_exporter/templates/blackbox.yml.j2
/home/dato/.cache/ansible-compat/cf2757/collections/ansible_collections/tina_pm/common/plugins/filter/toml_filter.py
```

It seems it correctly downloaded the latest versions of dependencies from Git?

**Comment by NightTsarina** [comment]
It seems that clearing the cache (which I did not even know existed!) solved the issue, sorry about the noise!

One small issue remains, though. If I checkout the latest commit (40dc1e1), the `.yamllint.yaml` is linted as a playbook and fails. I have no idea why, as the same file is present in other repos with no issue. Do you have any clue?
```
$ ansible-lint 
WARNING  Listing 1 violation(s) that are fatal
syntax-check[specific]: A playbook must be a list of plays, got a <class 'ansible.parsing.yaml.objects.AnsibleMapping'> instead: /home/tina/repos/Tina-pm/ansible/playbooks/.yamllint.yaml
.yamllint.yaml:3:1


                  Rule Violation Summary                   
 count tag                    profile rule associated tags 
     1 syntax-check[specific] min     core, unskippable    

Failed: 1 failure(s), 0 warning(s) on 56 files. Profile 'production' was required.
```

**Comment by dato** [comment]
Took I a bit to figure out, but I think your tree is not clean? (you get a count of 56 checked files, vs 54 on a clean checkout).

ansible-lint is being unhelpful in that it's printing a relative path, but the full path is hidden there at the end of the message:

>
> ```
> syntax-check[specific]: A playbook must be a list of plays, got a
> <class 'ansible.parsing.yaml.objects.AnsibleMapping'> instead:
> /home/tina/repos/Tina-pm/ansible/playbooks/.yamllint.yaml
>                                  ^^^^^^^^^
> ```

(FWIW I didn't notice the path either. I only discovered it after a while because I did a `cp .yamlllint.yaml playbooks` by hand on a hunch...)

Given #12 is merged, I think we can close this issue?

**Comment by dato** [comment]
I got the same error when running out of a submodule. Otherwise I could not reproduce.

**Comment by NightTsarina** [comment]
This is so weird.. I get the same error both from a submodule as well as from the normal clone. And in both cases it works well if I specify the lintables:

```
$ cd .collections/ansible_collections/tina_pm/playbooks

$ git show|head -1; ansible-lint --version
commit c8da89b22fdcc1b4dec973c77815b2cb8897482e
ansible-lint 24.10.0 using ansible-core:2.17.5 ansible-compat:24.9.1 ruamel-yaml:0.18.6 ruamel-yaml-clib:0.2.8

$ ansible-lint playbooks/

Passed: 0 failure(s), 0 warning(s) on 46 files. Profile 'production' was required, and it passed.

$ ansible-lint 
WARNING  Listing 1 violation(s) that are fatal
syntax-check[specific]: A playbook must be a list of plays, got a <class 'ansible.parsing.yaml.objects.AnsibleMapping'> instead: .../.collections/ansible_collections/tina_pm/playbooks/.yamllint.yaml
.yamllint.yaml:3:1


                  Rule Violation Summary                   
 count tag                    profile rule associated tags 
     1 syntax-check[specific] min     core, unskippable    

Failed: 1 failure(s), 0 warning(s) on 56 files. Profile 'production' was required.
```

In any case, at least now it seems to be linting correctly all the other files, so let' s close this
